project_id           = "YOUR_PROJECT_ID"
region               = "YOUR_REGION"
name                 = "my-cloud-function"
entry_point          = "trigger_pubsub"
location             = "YOUR_REGION"
source_archive_path  = "src/function-source.zip"
topic_name           = "my-topic"
cloud_run_url        = "YOUR_CLOUD_RUN_URL"
